### ISSUE TITLE
README claims stuff about `crypton` that applies to `cryptonite` only

### ISSUE THREAD

**Issue by andreasabel** [kazu-yamamoto/crypton#11]
I wonder whether the README needs update.  E.g. it claims
https://github.com/kazu-yamamoto/crypton/blob/cd903430d2053491b4846bcdec7b9fd2f94feb9a/README.md?plain=1#L32
This isn't true.  I checked and the first `crypton` release is in LTS 21.
LTS 3 - 20 have a release of `cryptonite`.  (LTS 21 has both `crypton` and `cryptonite`.)

There might be other stuff that isn't up to date anymore for the fork...

**Comment by kazu-yamamoto** [comment]
I don't use LTS since I'm a user of bare GHC and Cabal.
So, a PR to fix this issue is welcome.

**Comment by andreasabel** [comment]
#12 removes the problematic sentence.

**Comment by kazu-yamamoto** [comment]
Thank you!
