### ISSUE TITLE
`IV c` lacks ability to seq its internal bytearray

### ISSUE THREAD

**Issue by TheKK** [kazu-yamamoto/crypton#15]
Here's the definition of `IV c` (no `NFData` instance for it)
https://github.com/kazu-yamamoto/crypton/blob/50792f18be0ed3b1073439b4d48d344574f727cd/Crypto/Cipher/Types/Block.hs#L53

and we expose only the type without constructor
https://github.com/kazu-yamamoto/crypton/blob/50792f18be0ed3b1073439b4d48d344574f727cd/Crypto/Cipher/Types.hs#L28

These facts cause problem in my usage. I'll generate multiple `IV c`s by applying `ivAdd` multiple times (like scan initial IV with ivAdd, creates data in shape `iv0 'ivAdd' n0 'ivAdd' n1 'ivAdd' n2 ...` if no seq in each step) but only use them when certain condition is met, which is very likely to NOT use them at all most of the time.

Then I got visible thunk usage in heap even though I do run `seq` on `IV c`. Currently I use workaround, `let !_ = iv == iv`, to seq them.

Here are some ideas in my mind but it's hard to tell which one works best for this module:
- add strict annotation to `IV` constructor (behaviour changed on `seq`)
- create instance `NFData` for `IV c` (could evaluate too deep)
- add function to seq bytearray in `IV c` (which is rare solution in my experience)

Any new idea or thoughts are welcome :)

**Comment by kazu-yamamoto** [comment]
I would vote for adding `Strict` and `StrictData` to `crypton.cabal`

**Comment by TheKK** [comment]
`Strict` might be too aggressive in my opinion since it massively changes semantics of existed code in crypton and has chance to affect performance in good or bad way (please correct me if this is a wrong belief).

`StrictData` could be fine since it's easier to check and control its effect. I'll investigate this a little bit to see if we should solve these seq issues all at once or by cases.

**Comment by kazu-yamamoto** [comment]
`StrictData` only is a good step.
Would you add `StrictData` to the cabal file, test and send a PR?

**Comment by TheKK** [comment]
Sure, I'm glad to work on this!
