### ISSUE TITLE
Feature request: add TOTP / HOTP algorithms (RFC6238)

### ISSUE THREAD

**Issue by sigrdrifa** [kazu-yamamoto/crypton#20]
Would it be possible to add totp (and maybe hotp) algorithms for time-based one-time password approach? 

https://www.rfc-editor.org/rfc/rfc6238

or are these too specific to be in a general crypto sink package?

**Comment by kazu-yamamoto** [comment]
@sigrdrifa If you ask me to implement it, the answer is "no". I'm sorry.

If you ask merging your implementation to `crypton`, the answer is definitely "yes".

**Comment by sigrdrifa** [comment]
Okay great thanks, I might do a PR :)
