### ISSUE TITLE
hash entropy used in seedNew

### ISSUE THREAD

**Issue by epoberezkin** [kazu-yamamoto/crypton#22]
The motivation is to mitigate any compromise of system entropy source (that can be not even an entropy but some substitute, in case DoNotUseEntropy flag is used).

This line: https://github.com/kazu-yamamoto/crypton/blob/master/Crypto/Random.hs#L52

Replace this:

```
seedNew = Seed `fmap` getRandomBytes seedLength
```

with something like:

```
seedNew = Seed . take seedLength . BA.convert . (hash :: ByteString -> Digest SHA512) `fmap` getRandomBytes 64
```

It assumes that seedLength is less than 64 bytes, it's 40 in this file, but we could of course use some more "clever" approach and define something like getHashedRandomBytes that would get "random" bytes in 32/64 byte chunks, hash (256/512) and append them, and throw away what was unused. Given that more than 64 bytes almost never needed, it seems overkill.

cc @kazu-yamamoto - that would certainly be a good incentive to switch from cryptonite :)))

**Comment by kazu-yamamoto** [comment]
I don't understand this.
What is the purpose to squeeze `hash` between `Seed` and `getRandomBytes`?
`getRandomBytes` does not generate *pseudo* random but generate *real* random (e.g. from /dev/random).
Why hashing is necessary?

**Comment by epoberezkin** [comment]
The degree of its randomness depends on the source, e.g. for iOS we have to compile with DoNotUseEntropy flag, as iOS doesn't allow using getentropy, and on some other systems it can be also potentially comprisable sources: https://hackage.haskell.org/package/entropy-0.4.1.10/docs/System-Entropy.html

Hashing of entropy before using it as a seed is a common mitigation for attacks via RNG/entropy source.

https://blog.cr.yp.to/20140205-entropy.html
https://blog.cr.yp.to/20170723-random.html

[This refusal of NIST to hash the output of RNG](https://nvlpubs.nist.gov/nistpubs/FIPS/NIST.FIPS.203.ipd.pdf) (lines 309-314) in the standardised ML-KEM (Kyber) is the source of some [controversy](https://groups.google.com/a/list.nist.gov/g/pqc-forum/c/WFRDl8DqYQ4), as attacks via RNG are not uncommon.

**Comment by epoberezkin** [comment]
happy to make PR if it's ok

**Comment by kazu-yamamoto** [comment]
OK. I understand. I didn't know the iOS context.

Please send us a PR with your comment above.
