### ISSUE TITLE
Digest should be nominal in its type parameter

### ISSUE THREAD

**Issue by googleson78** [kazu-yamamoto/crypton#26]
Currently we can freely coerce between the `Digest`s of different hash algorithms. This can lead to safety issues, and to prevent it, we should make `Digest` have a `type role Digest nominal`

Example issue:
```haskell
> import Data.Coerce
> x :: Digest SHA256; x = undefined
> y = coerce @(Digest SHA256) @(Digest Blake2b_256) x
> :t y
y :: Digest Blake2b_256
```

**Comment by kazu-yamamoto** [comment]
Merged with a little fix.
Thank you for your contribution!
