### ISSUE TITLE
C symbol names clash with cryptonite

### ISSUE THREAD

**Issue by shlevy** [kazu-yamamoto/crypton#6]
If you have a package that transitively depends on both `crypton` and `cryptonite` (which we just saw due to an `http-client-tls` update), you get link errors (e.g. `multiple definition of 'cryptonite_sha512t_update'`).

**Comment by kazu-yamamoto** [comment]
I'm very sorry but I decided that network packages maintained by me go with `crypton`.
Michael is also OK to go with `crypton`.
So, WAI stuffs and `http-client-tls` now depends on `crypton`.
If you use these recent packages, please try to get rid of the dependency to `cryptonite`.
Or you can use `tls` 1.6.x to depend `cryptonite` only.

**Comment by shlevy** [comment]
I don't understand this response. Where did I suggest not using `crypton`?

The problem is that `crypton`'s C code uses the same symbol names (functions and non-static global variables) as `cryptonite`, and so they can't be used in the same project even transitively, and so any package switching from `cryptonite` to `crypton` is taking a breaking change.

This can be reasonably addressed in two ways:

1. Simply change the C files (e.g. rename the C function `cryptonite_sha512t_update` to `crypton_sha512t_update`)
2. Release new major versions of packages when they switch to `crypton`, and note in the relevant changelogs that downstream packages will have to do the same

1 is both simpler and more appropriate given that `crypton` is in fact a new package, but either would work and not lead to unexpected breakage of complex projects.

**Comment by shlevy** [comment]
Or possibly there is some linker setting to make the symbols from these C definitions only available within `crypton` and not exported beyond that.

**Comment by kazu-yamamoto** [comment]
I'm fine with the approach 1.
I will work for this on next Monday.

**Comment by angerman** [comment]
Thank you @shlevy for raising and detailing it. Thank you @kazu-yamamoto for offering to provide a prompt fix!

**Comment by angerman** [comment]
> Or possibly there is some linker setting to make the symbols from these C definitions only available within `crypton` and not exported beyond that.

Please no 🙈 that will mess with all the primitive linkers (like the one in GHC itself, or other exotic platforms) real bad.
